spring:
  application:
    name: sob-blog
  datasource:
    url: jdbc:mysql://localhost:3306/yiblogs
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
    password: 43798
yi.blog.image.save-path: /Users/yizhou/IdeaProjects/yiblog/src/main/resources/static/images
#2mb
yi.blog.image.max-size: 2097152
