spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 
            clientSecret: 
  application:
    name: sob-blog
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/yiblogs?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&&jdbcCompliantTruncation=false
    driver-class-name: com.mysql.jdbc.Driver
    username: yzhou116
    password: Sd!4888202
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 127.0.0.1
    password: 
yi.blog.image.save-path: /Users/yizhou/IdeaProjects/yiblog/src/main/resources/static/images
#2mb
yi.blog.image.max-size: 2097152
