package com.yizhou.yiblog.pojo.mapper;

import com.yizhou.yiblog.pojo.Article;
import org.springframework.context.annotation.Bean;
import org.springframework.stereotype.Repository;

import java.util.List;

public interface ArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    Article selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    List<Article> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int updateByPrimaryKey(Article record);
}