package com.yizhou.yiblog.pojo.mapper;

import com.yizhou.yiblog.pojo.Friends;

import java.util.List;

public interface FriendsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friends
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friends
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int insert(Friends record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friends
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    Friends selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friends
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    List<Friends> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_friends
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int updateByPrimaryKey(Friends record);
}