package com.yizhou.yiblog.pojo.mapper;

import com.yizhou.yiblog.pojo.Image;

import java.util.List;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    Image selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    List<Image> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_images
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int updateByPrimaryKey(Image record);
}