package com.yizhou.yiblog.pojo.mapper;

import com.yizhou.yiblog.pojo.Labels;

import java.util.List;

public interface LabelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_labels
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_labels
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int insert(Labels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_labels
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    Labels selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_labels
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    List<Labels> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_labels
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int updateByPrimaryKey(Labels record);
}