package com.yizhou.yiblog.pojo.mapper;

import com.yizhou.yiblog.pojo.Settings;

import java.util.List;

public interface SettingsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_settings
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_settings
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int insert(Settings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_settings
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    Settings selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_settings
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    List<Settings> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_settings
     *
     * @mbg.generated Sat Jan 09 23:46:26 EST 2021
     */
    int updateByPrimaryKey(Settings record);
}